project_id = "zwglefxogjaivkuebdda"

[functions.bot-post]
verify_jwt = false

[functions.reset-test-passwords]
verify_jwt = false

[functions.create-pix-payment]
verify_jwt = false

[functions.webhook-mercadopago]
verify_jwt = false

[functions.track-referral]
verify_jwt = false
