// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { mockFetch } from './mockFetch';

const getEnv = (name: string) => {
  if (typeof process !== 'undefined' && process.env[name]) return process.env[name];
  try {
    // @ts-ignore - import.meta.env is only available in Vite
    return import.meta.env[name];
  } catch (e) {
    return undefined;
  }
};

const SUPABASE_URL = getEnv('VITE_SUPABASE_URL');
const SUPABASE_PUBLISHABLE_KEY = getEnv('VITE_SUPABASE_PUBLISHABLE_KEY') || getEnv('VITE_SUPABASE_ANON_KEY');

const isMock = !SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY || SUPABASE_URL.includes('xyz');

export const supabase = createClient<Database>(
  isMock ? 'https://mock-supabase.co' : SUPABASE_URL!,
  isMock ? 'mock-key' : SUPABASE_PUBLISHABLE_KEY!,
  {
    global: {
      fetch: isMock ? mockFetch : fetch,
    },
    auth: {
      storage: typeof window !== 'undefined' ? window.localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    }
  }
);